---
# tasks file for ansible-role-image-resize

  - name: Install ImageMagick package
    yum: name=ImageMagick state=present
    register: installed_imagemagick

  - name: Add use_default_img=true if new image is not specified.
    set_fact: "use_default_img=true"
    when: "{{input_img == 'sample-openshift-ori.png'}}"

  - name: Copy sample image if new image is not specified.
    copy: src=sample-openshift-ori.png dest=/tmp/
    when: "{{use_default_img}}"

  - name: Change input_img path when sample image is used.
    set_fact: input_img="/tmp/{{input_img}}"
    when: "{{use_default_img}}"

  - name: Check if the output_img exist
    stat: path={{output_img}}
    register: stat_output_img_exist

  - name: Resize image with specific size
    command: convert {{input_img}} -resize {{size}} {{output_img}}
    when: stat_output_img_exist.stat.exists == true and "{{force != true}}"
